// <auto-generated />
using System;
using System.Collections.Generic;
using Crash.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crash.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240322175322_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Crash.Models.Entities.Accident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccidentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AccidentId")
                        .HasColumnType("integer");

                    b.Property<string>("Daylight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("EstimatedCost")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfParties")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Parties")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Accidents");
                });

            modelBuilder.Entity("Crash.Models.Entities.Images", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<Guid>("AccidentId")
                    .HasColumnType("uuid");

                b.Property<List<string>>("ImageData")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.HasKey("Id");

                b.ToTable("Images");
            });
#pragma warning restore 612, 618
        }
    }
}
